name: intrusion-detector-api

channels:
  - conda-forge

dependencies:
  - python=3.10
  - pip
  - pip:
      - pandas==1.5.3
      - scikit-learn==1.2.1
      - joblib===1.2.0
      - fastapi==0.65.2
      - uvicorn==0.14.0
      - boto3==1.26.106
      - prometheus-fastapi-instrumentator==6.0.0
      - prometheus-client==0.16.0 